<a href="https://colab.research.google.com/github/gitmystuff/DSChunks/blob/main/Week_02-The_Research_Question/Week_02_In_Class_Activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 2: In-Class Activity

Your Name

## Getting Started

* Colab - get notebook from gitmystuff DTSC4080 repository
* Save a Copy in Drive
* Remove Copy of
* Edit your name
* Attendance
* Clean up Colab Notebooks folder
* Submit shared link

## Natural Language Processing

## The Research Question

* LinkedIn Transcript
* Bard Summary Keypoints
* Prompt Engineering - https://towardsdatascience.com/summarising-best-practices-for-prompt-engineering-c5e86c483af4

## Bard

* https://support.google.com/bard/answer/13695044?hl=en&visit_id=638417504398034592-2218294070&p=lm_ws_ext&rd=1#link_ws

**Prompt**: help me write a research question about the leading causes of ultra nationalism

I can definitely help you craft a research question about the leading causes of ultra-nationalism! To make it even more effective, I need some additional information from you:

* **What specific aspect of ultra-nationalism are you most interested in?**  For example, you could focus on its emergence in specific countries, its online and social media presence, its relationship to economic hardship, or its historical precedents.
* **What level of analysis are you interested in?** Are you looking for broad overarching factors, or more nuanced and specific reasons within a particular context?
* **What theoretical frameworks or approaches are you interested in exploring?** This could include political science, sociology, psychology, history, or even cultural studies.

Once you have a clearer idea of these factors, I can help you formulate a research question that is both interesting and feasible. Here are some examples to get you started:

**Broad questions:**

* **What are the main social, economic, and political factors that contribute to the rise of ultra-nationalism in different societies?**
* **How has the digital age and the spread of social media impacted the development and dissemination of ultra-nationalist ideologies?**
* **To what extent is economic hardship or a sense of national decline a trigger for ultra-nationalist movements?**

**More specific questions:**

* **How has the history of colonization and national humiliation contributed to the rise of ultra-nationalism in India?**
* **What role do populist leaders and rhetoric play in mobilizing and legitimizing ultra-nationalist sentiments in the United States?**
* **How do online communities and echo chambers facilitate the radicalization and spread of ultra-nationalist ideas among young people?**

By considering these examples and providing me with additional information about your specific interests, I can help you refine your research question and set the stage for a successful exploration of this complex and timely topic.

I hope this helps!

## Mounting Google Drive

## Beautiful Soup

In [ ]:
# get table of contents
from bs4 import BeautifulSoup
import pandas as pd
import requests

soup = BeautifulSoup(requests.get("https://en.wikipedia.org/wiki/Outline_of_the_history_of_Western_civilization").text)
s = soup.find_all('span', {'class' : 'mw-headline'})
s_list = [x.get_text() for x in s]
s_series = pd.Series(s_list)
toc = s_series.to_frame()
toc.columns = ['header']
toc.to_csv('toc.csv', index=False)
toc.head()

In [ ]:
# pip install wikipedia

In [ ]:
import pandas as pd

kws = pd.read_csv('/content/drive/MyDrive/INFO4080/Week 02 - The Research Question/toc.csv')
# kws.head()
# kws.iloc[0].header

'Nature of Western civilization'

## Wikipedia API

If you intend to do any scraping projects or automated requests, consider alternatives such as Pywikipediabot or MediaWiki API, which has other superior features.

* wikipedia.search('keywords', results=2)
* wikipedia.suggest('keyword')
* wikipedia.summary('keywords', sentences=2)
* wikipedia.page('keywords')
* wikipedia.page('keywords').content
* wikipedia.page('keywords').references
* wikipedia.page('keywords').title
* wikipedia.page('keywords').url
* wikipedia.page('keywords').categories
* wikipedia.page('keywords').content
* wikipedia.page('keywords').links
* wikipedia.geosearch(33.2075, 97.1526)
* wikipedia.set_lang('hi')
* wikipedia.languages()
* wikipedia.page('keywords').images[0]
* wikipedia.page('keywords').html()

In [ ]:
import wikipedia

idx = 1
results = 4
components = results
topics = 10

print(kws.iloc[idx])
wikipedia.search(kws.iloc[idx].header, results=results)

header    Antiquity: before 500
Name: 1, dtype: object

['Outline of the history of Western civilization',
 'Metals of antiquity',
 'Late antiquity',
 'Poland in antiquity']

In [ ]:
titles = wikipedia.search(kws.iloc[idx].header, results=results)
# print(titles)
for title in titles:
  print(wikipedia.page(title).url)

https://en.wikipedia.org/wiki/Outline_of_the_history_of_Western_civilization
https://en.wikipedia.org/wiki/Metals_of_antiquity
https://en.wikipedia.org/wiki/Late_antiquity
https://en.wikipedia.org/wiki/Poland_in_antiquity

In [ ]:
# https://stackoverflow.com/questions/61651052/find-exact-match-of-a-wikipedia-page-title-using-python

data = []
for title in titles:
  # print(title)
  # print()
  try:
      if wikipedia.page(title).title != title:
          print("no wikipedia page")
      else:
          # print(wikipedia.summary(title, sentences=5))
          data.append([title, wikipedia.page(title).content, wikipedia.summary(title, sentences=5)])
  except:
      print(title + " not found.")

df = pd.DataFrame(data, columns=['title', 'content', 'summary'])
df.head()

,title,content,summary
0,Outline of the history of Western civilization,The following outline is provided as an overvi...,The following outline is provided as an overvi...
1,Metals of antiquity,The metals of antiquity are the seven metals w...,The metals of antiquity are the seven metals w...
2,Late antiquity,Late antiquity is sometimes defined as spannin...,Late antiquity is sometimes defined as spannin...
3,Poland in antiquity,Poland in antiquity was characterized by peopl...,Poland in antiquity was characterized by peopl...

## LDA (Latent Dirichlet Allocation)

In natural language processing, latent Dirichlet allocation (LDA) is a Bayesian network (and, therefore, a generative statistical model) for modeling automatically extracted topics in textual corpora. The LDA is an example of a Bayesian topic model. In this, observations (e.g., words) are collected into documents, and each word's presence is attributable to one of the document's topics. Each document will contain a small number of topics.

Sources:
 * https://en.wikipedia.org/wiki/Latent_Dirichlet_allocation
 * https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.LatentDirichletAllocation.html

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')
vectors = vectorizer.fit_transform(df['summary'].values.astype('U'))

model = LatentDirichletAllocation(n_components=components)
model.fit(vectors)

topics_dictionary = {}
for index, topic in enumerate(model.components_):
    print(f'Topic {index} top words: {[vectorizer.get_feature_names_out()[i] for i in topic.argsort()[-topics:]]}')
    topics_dictionary[index] = [vectorizer.get_feature_names_out()[i] for i in topic.argsort()[-topics:]]

topics_dictionary

Topic 0 top words: ['later', 'situation', 'recognised', 'europe', 'classical', 'elemental', 'seven', 'antiquity', 'known', 'metals']
Topic 1 top words: ['antiquity', 'identified', 'century', 'iron', 'time', 'south', 'end', 'world', 'classical', 'europe']
Topic 2 top words: ['ancient', 'century', 'antiquity', 'archeological', 'poland', 'civilizations', 'late', 'period', 'western', 'civilization']
Topic 3 top words: ['antiquity', 'identified', 'century', 'iron', 'time', 'south', 'end', 'world', 'classical', 'europe']

{0: ['later',
  'situation',
  'recognised',
  'europe',
  'classical',
  'elemental',
  'seven',
  'antiquity',
  'known',
  'metals'],
 1: ['antiquity',
  'identified',
  'century',
  'iron',
  'time',
  'south',
  'end',
  'world',
  'classical',
  'europe'],
 2: ['ancient',
  'century',
  'antiquity',
  'archeological',
  'poland',
  'civilizations',
  'late',
  'period',
  'western',
  'civilization'],
 3: ['antiquity',
  'identified',
  'century',
  'iron',
  'time',
  'south',
  'end',
  'world',
  'classical',
  'europe']}

In [ ]:
topic_results = model.transform(vectors)
df['topic_idx'] = topic_results.argmax(axis=1)
df.head()

,title,content,summary,topic_idx
0,Outline of the history of Western civilization,The following outline is provided as an overvi...,The following outline is provided as an overvi...,2
1,Metals of antiquity,The metals of antiquity are the seven metals w...,The metals of antiquity are the seven metals w...,0
2,Late antiquity,Late antiquity is sometimes defined as spannin...,Late antiquity is sometimes defined as spannin...,2
3,Poland in antiquity,Poland in antiquity was characterized by peopl...,Poland in antiquity was characterized by peopl...,2

In [ ]:
def get_topics(row):
  return ', '.join([top for top in topics_dictionary[row.topic_idx]])

df['topics']= df.apply(get_topics, axis=1)
df.head()

,title,content,summary,topic_idx,topics
0,Outline of the history of Western civilization,The following outline is provided as an overvi...,The following outline is provided as an overvi...,2,"ancient, century, antiquity, archeological, po..."
1,Metals of antiquity,The metals of antiquity are the seven metals w...,The metals of antiquity are the seven metals w...,0,"later, situation, recognised, europe, classica..."
2,Late antiquity,Late antiquity is sometimes defined as spannin...,Late antiquity is sometimes defined as spannin...,2,"ancient, century, antiquity, archeological, po..."
3,Poland in antiquity,Poland in antiquity was characterized by peopl...,Poland in antiquity was characterized by peopl...,2,"ancient, century, antiquity, archeological, po..."

## SpaCy

* https://spacy.io/
* https://medium.com/analytics-vidhya/text-summarization-using-spacy-ca4867c6b744

In [1]:
import spacy.cli

spacy.cli.download('en_core_web_sm')
nlp = spacy.load('en_core_web_sm')

✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

## Language Model and Pipelines

en_core_web_sm

* https://www.kdnuggets.com/2021/03/natural-language-processing-pipelines-explained.html
* https://spacy.io/usage/spacy-101
* https://en.wikipedia.org/wiki/Language_model
* https://builtin.com/data-science/beginners-guide-language-models

In [2]:
import spacy
from spacy.lang.en.stop_words import STOP_WORDS
from string import punctuation
from collections import Counter
from heapq import nlargest

nlp = spacy.load('en_core_web_sm')

In [ ]:
# doc = nlp(df.loc[0]['content'])
summary_text = ' '.join([txt for txt in df.summary])
# print(summary_text)
doc = nlp(summary_text)
len(list(doc.sents))
keyword = []
stopwords = list(STOP_WORDS)
pos_tag = ['PROPN', 'ADJ', 'NOUN', 'VERB']
for token in doc:
    if(token.text in stopwords or token.text in punctuation):
        continue
    if(token.pos_ in pos_tag):
        keyword.append(token.text)

# count most frequent words
freq_word = Counter(keyword)
print(freq_word.most_common(5))

# normalize for better processing
max_freq = Counter(keyword).most_common(1)[0][1]
for word in freq_word.keys():
    freq_word[word] = (freq_word[word]/max_freq)

print(freq_word.most_common(5))

[('antiquity', 7), ('Western', 6), ('civilization', 6), ('metals', 6), ('century', 5)]
[('antiquity', 1.0), ('Western', 0.8571428571428571), ('civilization', 0.8571428571428571), ('metals', 0.8571428571428571), ('century', 0.7142857142857143)]

In [ ]:
# weights based on frequency
sent_strength={}
for sent in doc.sents:
    for word in sent:
        if word.text in freq_word.keys():
            if sent in sent_strength.keys():
                sent_strength[sent] += freq_word[word.text]
            else:
                sent_strength[sent] = freq_word[word.text]

print(sent_strength)

{The following outline is provided as an overview of and topical guide to the history of Western civilization:
History of Western civilization – record of the development of human civilization beginning in Ancient Greece and Ancient Rome, and generally spreading westwards.
: 7.714285714285716, Ancient Greek science, philosophy, democracy, architecture, literature, and art provided a foundation embraced and built upon by the Roman Empire as it swept up Europe, including the Hellenic world in its conquests in the 1st century BC.: 6.000000000000001, From its European and Mediterranean origins, Western civilization has spread to produce the dominant cultures of modern North America, South America, and much of Oceania, and has had immense global influence in recent centuries.


: 5.42857142857143, == Nature of Western civilization ==
Western world – The first civilizations made various unique contributions to the western civilizations.: 5.0, These contributions, which are likewise the achievements of antiquated civilizations, incorporate certain things in the zones of philosophy, art and engineering, and math and science.: 3.2857142857142847, The antiquated civilizations were a momentous civilization in that they have made every one of these contributions and achievements while at the same time battling.: 2.9999999999999996, The metals of antiquity are the seven metals which humans had identified and found use for in prehistoric times in Africa, Europe and throughout Asia: gold, silver, copper, tin, lead, iron, and mercury.: 5.571428571428574, These seven are the metals from which the classical world was forged.
: 1.857142857142857, Zinc, arsenic, and antimony were also known during antiquity, but they were not recognised as distinct metals until later.: 3.142857142857143, A special case is platinum; it was known to native South Americans around the time Europe was going through classical antiquity, but was unknown to Europeans until the 18th century.: 5.142857142857143, Thus, at most eleven elemental metals and metalloids were known by the end of antiquity; this contrasts greatly with the situation today, with over 90 elemental metals known.: 5.428571428571428, Late antiquity is sometimes defined as spanning from the end of classical antiquity to the local start of the Middle Ages, from around the late 3rd century up to the 7th or 8th century in Europe and adjacent areas bordering the Mediterranean Basin depending on location.: 8.142857142857144, The popularisation of this periodization in English has generally been credited to historian Peter Brown, who proposed a period between 150-750 AD..: 1.9999999999999996, The Oxford Centre for Late Antiquity defines it as "the period between approximately 250 and 750 CE".  : 1.5714285714285712, Precise boundaries for the period are a continuing matter of debate.: 1.2857142857142856, In the West, its end was earlier, with the start of the Early Middle Ages typically placed in the 6th century, or even earlier on the edges of the Western Roman Empire.: 4.285714285714286, Poland in antiquity was characterized by peoples from various archeological cultures  living in and migrating through various parts of what is now Poland, from about 400 BC to 450–500 AD.: 4.142857142857142, These people are identified as Slavs, Celts, Germanic peoples, Balts, Thracians, Avars, and Scythians.: 1.8571428571428568, Other groups, difficult to identify, were most likely also present, as the ethnic composition of archeological cultures is often poorly recognized.: 2.285714285714285, While lacking any written language to speak of, many of them developed a relatively advanced material culture and social organization, as evidenced by the archeological record; for example, richly furnished, "princely" dynastic graves.
: 2.8571428571428563, Characteristic of the period was a high rate of migration of large groups of people, even equivalents of modern nations.: 2.428571428571428, This article covers the continuation of the Iron Age (see Bronze and Iron Age Poland), the La Tène and Roman influence, and Migration periods.: 3.4285714285714275}

In [ ]:
import textwrap

summary = nlargest(10, sent_strength, key=sent_strength.get)
summary = ' '.join([w.text for w in summary])
print(textwrap.fill(summary, 100))

Late antiquity is sometimes defined as spanning from the end of classical antiquity to the local
start of the Middle Ages, from around the late 3rd century up to the 7th or 8th century in Europe
and adjacent areas bordering the Mediterranean Basin depending on location. The following outline is
provided as an overview of and topical guide to the history of Western civilization: History of
Western civilization – record of the development of human civilization beginning in Ancient Greece
and Ancient Rome, and generally spreading westwards.  Ancient Greek science, philosophy, democracy,
architecture, literature, and art provided a foundation embraced and built upon by the Roman Empire
as it swept up Europe, including the Hellenic world in its conquests in the 1st century BC. The
metals of antiquity are the seven metals which humans had identified and found use for in
prehistoric times in Africa, Europe and throughout Asia: gold, silver, copper, tin, lead, iron, and
mercury. From its European and Mediterranean origins, Western civilization has spread to produce the
dominant cultures of modern North America, South America, and much of Oceania, and has had immense
global influence in recent centuries.    Thus, at most eleven elemental metals and metalloids were
known by the end of antiquity; this contrasts greatly with the situation today, with over 90
elemental metals known. A special case is platinum; it was known to native South Americans around
the time Europe was going through classical antiquity, but was unknown to Europeans until the 18th
century. == Nature of Western civilization == Western world – The first civilizations made various
unique contributions to the western civilizations. In the West, its end was earlier, with the start
of the Early Middle Ages typically placed in the 6th century, or even earlier on the edges of the
Western Roman Empire. Poland in antiquity was characterized by peoples from various archeological
cultures  living in and migrating through various parts of what is now Poland, from about 400 BC to
450–500 AD.

## Research in Antiquity

* https://en.wikipedia.org/wiki/Science_in_the_ancient_world
* https://en.wikipedia.org/wiki/Science_in_classical_antiquity

## Looker Studio Introduction

### Data

* https://data.worldbank.org/indicator/SP.POP.TOTL
* https://simple.wikipedia.org/wiki/List_of_countries_by_continents

In [5]:
# ctrl - h find and replace
import pandas as pd

africa = pd.read_html('https://simple.wikipedia.org/wiki/List_of_countries_by_continents', header=0)[0]
africa['continent'] = 'Africa'
africa.columns = africa.columns.str.strip().str.lower()
print(africa.shape)
africa.head()

(54, 9)

,unnamed: 0,flag,english names [1][2][3][4],capital [3][5][6],population 2021 [7][8],area[a][b] [9],currency [3],map,continent
0,1,NaN,Algeria,Algiers,44177969,"2,381,740 km2 (919,595 sq mi)",Algerian dinar,NaN,Africa
1,2,NaN,Angola,Luanda,34503774,"1,246,700 km2 (481,354 sq mi)",kwanza,NaN,Africa
2,3,NaN,Benin,Porto-Novo,12996895,"112,622 km2 (43,484 sq mi)",CFA franc,NaN,Africa
3,4,NaN,Botswana,Gaborone,2588423,"581,726 km2 (224,606 sq mi)",pula,NaN,Africa
4,5,NaN,Burkina Faso,Ouagadougou,22100683,"274,000 km2 (105,792 sq mi)",CFA franc,NaN,Africa

In [7]:
cols = ['delete', 'flag', 'country', 'capital', 'population', 'area', 'currency', 'map', 'continent']
africa.columns = cols
africa.head()

,delete,flag,country,capital,population,area,currency,map,continent
0,1,NaN,Algeria,Algiers,44177969,"2,381,740 km2 (919,595 sq mi)",Algerian dinar,NaN,Africa
1,2,NaN,Angola,Luanda,34503774,"1,246,700 km2 (481,354 sq mi)",kwanza,NaN,Africa
2,3,NaN,Benin,Porto-Novo,12996895,"112,622 km2 (43,484 sq mi)",CFA franc,NaN,Africa
3,4,NaN,Botswana,Gaborone,2588423,"581,726 km2 (224,606 sq mi)",pula,NaN,Africa
4,5,NaN,Burkina Faso,Ouagadougou,22100683,"274,000 km2 (105,792 sq mi)",CFA franc,NaN,Africa

In [9]:
africa.drop(['delete', 'flag', 'map'], axis=1, inplace=True)
print(africa.shape)
africa.head()

(54, 6)

,country,capital,population,area,currency,continent
0,Algeria,Algiers,44177969,"2,381,740 km2 (919,595 sq mi)",Algerian dinar,Africa
1,Angola,Luanda,34503774,"1,246,700 km2 (481,354 sq mi)",kwanza,Africa
2,Benin,Porto-Novo,12996895,"112,622 km2 (43,484 sq mi)",CFA franc,Africa
3,Botswana,Gaborone,2588423,"581,726 km2 (224,606 sq mi)",pula,Africa
4,Burkina Faso,Ouagadougou,22100683,"274,000 km2 (105,792 sq mi)",CFA franc,Africa

In [ ]:
# continents = pd.concat([], ignore_index=True)
# print(continents.shape)
# print(continents.info())
# continents.sample(5)

## Descriptive Analysis

Descriptive analytics is the process of using current and historical data to identify trends and relationships. It’s sometimes called the simplest form of data analysis because it describes trends and relationships but doesn’t dig deeper.

https://online.hbs.edu/blog/post/descriptive-analytics

In [15]:
import pandas as pd

df = pd.read_csv('https://docs.google.com/spreadsheets/d/18tZbDl8q8u3hktyWHQYDjprn8KUKqK4AgZTKXU4J0gM/export?format=csv')
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54608.0,55811.0,56682.0,57475.0,58178.0,58782.0,...,102880.0,103594.0,104257.0,104874.0,105439.0,105962.0,106442.0,106585.0,106537.0,106445.0
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130692579.0,134169237.0,137835590.0,141630546.0,145605995.0,149742351.0,...,567892149.0,583651101.0,600008424.0,616377605.0,632746570.0,649757148.0,667242986.0,685112979.0,702977106.0,720859132.0
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8622466.0,8790140.0,8969047.0,9157465.0,9355514.0,9565147.0,...,31541209.0,32716210.0,33753499.0,34636207.0,35643418.0,36686784.0,37769499.0,38972230.0,40099462.0,41128771.0
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97256290.0,99314028.0,101445032.0,103667517.0,105959979.0,108336203.0,...,387204553.0,397855507.0,408690375.0,419778384.0,431138704.0,442646825.0,454306063.0,466189102.0,478185907.0,490330870.0
4,Angola,AGO,"Population, total",SP.POP.TOTL,5357195.0,5441333.0,5521400.0,5599827.0,5673199.0,5736582.0,...,26147002.0,27128337.0,28127721.0,29154746.0,30208628.0,31273533.0,32353588.0,33428486.0,34503774.0,35588987.0

In [16]:
df.describe()

,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
count,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,2.640000e+02,...,2.650000e+02,2.650000e+02,2.650000e+02,2.650000e+02,2.650000e+02,2.650000e+02,2.650000e+02,2.650000e+02,2.650000e+02,2.650000e+02
mean,1.172712e+08,1.188807e+08,1.210511e+08,1.237333e+08,1.264378e+08,1.291813e+08,1.320404e+08,1.348980e+08,1.378358e+08,1.408789e+08,...,2.927593e+08,2.966353e+08,3.004815e+08,3.043263e+08,3.081770e+08,3.119641e+08,3.156701e+08,3.192595e+08,3.225221e+08,3.254733e+08
std,3.695439e+08,3.740897e+08,3.808061e+08,3.895039e+08,3.982439e+08,4.071153e+08,4.164504e+08,4.257424e+08,4.353218e+08,4.452927e+08,...,9.186237e+08,9.300118e+08,9.412522e+08,9.524238e+08,9.636041e+08,9.744884e+08,9.850405e+08,9.951225e+08,1.004225e+09,1.012163e+09
min,2.646000e+03,2.888000e+03,3.171000e+03,3.481000e+03,3.811000e+03,4.161000e+03,4.531000e+03,4.930000e+03,5.354000e+03,5.646000e+03,...,1.069400e+04,1.089900e+04,1.087700e+04,1.085200e+04,1.082800e+04,1.086500e+04,1.095600e+04,1.106900e+04,1.120400e+04,1.131200e+04
25%,5.132212e+05,5.231345e+05,5.337595e+05,5.449288e+05,5.566630e+05,5.651150e+05,5.691470e+05,5.773872e+05,5.832700e+05,5.875942e+05,...,1.697753e+06,1.743309e+06,1.788196e+06,1.777557e+06,1.791003e+06,1.797085e+06,1.788878e+06,1.790133e+06,1.786038e+06,1.761985e+06
50%,3.757486e+06,3.887144e+06,4.023896e+06,4.139356e+06,4.224612e+06,4.277636e+06,4.331825e+06,4.385700e+06,4.450934e+06,4.530800e+06,...,1.014958e+07,1.028212e+07,1.035808e+07,1.032545e+07,1.030030e+07,1.039533e+07,1.044767e+07,1.060623e+07,1.050577e+07,1.048694e+07
75%,2.670606e+07,2.748694e+07,2.830289e+07,2.914708e+07,3.001684e+07,3.084892e+07,3.163010e+07,3.209247e+07,3.249927e+07,3.277149e+07,...,6.023395e+07,6.078914e+07,6.073058e+07,6.062750e+07,6.053671e+07,6.042176e+07,5.987258e+07,6.170452e+07,6.358833e+07,6.549775e+07
max,3.031474e+09,3.072422e+09,3.126850e+09,3.193429e+09,3.260442e+09,3.328209e+09,3.398480e+09,3.468371e+09,3.540164e+09,3.614573e+09,...,7.229303e+09,7.317040e+09,7.403850e+09,7.490415e+09,7.576442e+09,7.660371e+09,7.741775e+09,7.820206e+09,7.888306e+09,7.950947e+09

In [33]:
world_pop = df.melt(id_vars=['Country Name'], value_vars=['2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022'])
world_pop.columns = ['Country', 'Year', 'Population']
world_pop.to_csv('wrld_pop.csv', index=False)
world_pop.head()

                       Country  Year   Population
0                        Aruba  2012     102112.0
1  Africa Eastern and Southern  2012  552530654.0
2                  Afghanistan  2012   30466479.0
3   Africa Western and Central  2012  376797999.0
4                       Angola  2012   25188292.0

## Notes

https://www.linkedin.com/learning/looker-studio-for-beginners/harness-the-power-of-looker-studio?autoplay=true&resume=false&u=74650474

* csv to Google Sheets
* Create (Authorize)
* Connection
* URL - Sheet ID
* Connect
* Create Report
* Delete Auto Generated Table
* Check Field Types, Resource, Manage added data sources
* Edit Data Source, check for Geo (Percentage) fields
* Check Default Aggregation
* Done, Close, Name Report
* Add a Chart (Basic Column)
* Drop Year over Country
* Population over Record Count (Add metric)
* Fix Sort
* Insert Menu (Controls), Drop Down List
* Drag right above the bars, top right
* Shift arrow to micro move box
* Change Year to Country, with list highlighted, drag drop Country over Year
* Select View Mode and play around
* Make sure Country (all) is selected and go back to Edit mode
* Create link for the drop down, left click filter and then Ctrl click bar chart, click on Arrange and then Group
* Add a Pie chart below the bar chart
* Replace year dimension with country
* Add a year drop down box, change country to year, and group
* View and play around
* Add Continent data source and blend data
* Edit mode, click on Resource, Manage added data sources
* Add a data source (File upload), Continents
* If uploading, wait for green do to appear before adding
* Click on Add and Add to Report
* Create a blend
* Select pie chart till Chart Setup appears
* Blend Data, join another table
* Add dimension Year (Pop Data) and Continent
* Configure join (Left outer) https://learnsql.com/blog/learn-and-practice-sql-joins/
* Confirm Country Link Relationship and Save Save
* Confirm Population Metric
* Use Continent as Dimension
* View and play

## Create Quiz Items