# Titanic Passengers

Scraped from Wikipedia

* https://www.kaggle.com/code/pavlofesenko/extending-titanic-dataset-using-wikipedia
* https://pandas.pydata.org/docs/reference/api/pandas.read_html.html
* https://pandas.pydata.org/docs/user_guide/io.html#io-read-html
* https://en.wikipedia.org/wiki/Passengers_of_the_Titanic
* https://en.wikipedia.org/wiki/Crew_of_the_Titanic

In [1]:
# pip install html5lib

In [2]:
import pandas as pd

first_class = pd.read_html('https://en.wikipedia.org/wiki/Passengers_of_the_Titanic', header=0)[1]
first_class['pclass'] = 1
first_class.columns = first_class.columns.str.strip().str.lower()
print(first_class.shape)
first_class.head()

(326, 8)

,name,age,hometown,boarded,destination,lifeboat,body,pclass
0,"Allen, Miss Elizabeth Walton",29,"St Louis, Missouri, US",Southampton,St Louis,NaN,NaN,1
1,"Allison, Mr. Hudson Creighton",30,"Montreal, Quebec, Canada",Southampton,"Montreal, Quebec, Canada",NaN,135MB,1
2,"and chauffeur, Mr. George Swane[70]",19,NaN,Southampton,"Montreal, Quebec, Canada",NaN,294MB,1
3,"and cook, Miss Amelia Mary ""Mildred"" Brown[70]",18,"London, England, UK",Southampton,"Montreal, Quebec, Canada",11,NaN,1
4,"Allison, Mrs. Bessie Waldo (née Daniels)",25,"Montreal, Quebec, Canada",Southampton,"Montreal, Quebec, Canada",NaN,NaN,1

In [3]:
from bs4 import BeautifulSoup
import pandas as pd
import requests

soup = BeautifulSoup(requests.get("https://en.wikipedia.org/wiki/Passengers_of_the_Titanic").text)
s = soup.select_one('table:nth-of-type(2)').find_all('tr', {'style': 'background:#9bddff;'})
s_list = [x.text.split('\n')[1] for x in s]
s_series = pd.Series(s_list)
first_class_survivors = s_series.to_frame()
first_class_survivors.columns = ['survivors']
first_class_survivors.head()

                                        survivors
0                    Allen, Miss Elizabeth Walton
1  and cook, Miss Amelia Mary "Mildred" Brown[70]
2                    and maid, Miss Sarah Daniels
3                   Allison, Master Hudson Trevor
4         and nurse, Miss Alice Catherine Cleaver

In [4]:
soup = BeautifulSoup(requests.get("https://en.wikipedia.org/wiki/Passengers_of_the_Titanic").text)
rows = soup.select_one('table:nth-of-type(2)').find_all('tr')
psurvived = []
for row in rows[1:]:
    cells = row.find_all('td')
    pname = cells[0].get_text()
    if row.has_attr('style'):
        psurvived.append((pname, 1))
    else:
        psurvived.append((pname, 0))

survived = pd.DataFrame(psurvived, columns=['name', 'survived'])
# survived.head()
pfirst_class = pd.merge(first_class, survived, on='name')
pfirst_class.head()

,name,age,hometown,boarded,destination,lifeboat,body,pclass,survived
0,"Allen, Miss Elizabeth Walton",29,"St Louis, Missouri, US",Southampton,St Louis,NaN,NaN,1,1
1,"Allison, Mr. Hudson Creighton",30,"Montreal, Quebec, Canada",Southampton,"Montreal, Quebec, Canada",NaN,135MB,1,0
2,"and chauffeur, Mr. George Swane[70]",19,NaN,Southampton,"Montreal, Quebec, Canada",NaN,294MB,1,0
3,"and cook, Miss Amelia Mary ""Mildred"" Brown[70]",18,"London, England, UK",Southampton,"Montreal, Quebec, Canada",11,NaN,1,1
4,"Allison, Mrs. Bessie Waldo (née Daniels)",25,"Montreal, Quebec, Canada",Southampton,"Montreal, Quebec, Canada",NaN,NaN,1,0

In [5]:
second_class = pd.read_html('https://en.wikipedia.org/wiki/Passengers_of_the_Titanic', header=0)[2]
second_class['pclass'] = 2
second_class.columns = second_class.columns.str.strip().str.lower()
print(second_class.shape)
second_class.head()

(278, 8)

,name,age,hometown,boarded,destination,lifeboat,body,pclass
0,"Abelson, Mr. Samuel",30,Russia,Cherbourg,"New York, New York, US",NaN,NaN,2
1,"Abelson, Mrs. Anna (née Wizosky?)",28,Russia,Cherbourg,"New York, New York, US",10,NaN,2
2,"Andrew, Mr. Edgar Samuel",17,"San Ambrosio, Córdoba, Argentina",Southampton,"Trenton, New Jersey, US",NaN,NaN,2
3,"Andrew, Mr. Frank Thomas",30,"Redruth, Cornwall, England",Southampton,"Houghton, Michigan, US",NaN,NaN,2
4,"Angle, Mr. William A.",32,"Warwick, Warwickshire, England",Southampton,New York City,NaN,NaN,2

In [6]:
rows = soup.select_one('table:nth-of-type(3)').find_all('tr')
psurvived = []
for row in rows[1:]:
    cells = row.find_all('td')
    pname = cells[0].get_text()
    if row.has_attr('style'):
        psurvived.append((pname, 1))
    else:
        psurvived.append((pname, 0))

survived = pd.DataFrame(psurvived, columns=['name', 'survived'])
# survived.head()
psecond_class = pd.merge(second_class, survived, on='name')
psecond_class.head()

,name,age,hometown,boarded,destination,lifeboat,body,pclass,survived
0,"Abelson, Mr. Samuel",30,Russia,Cherbourg,"New York, New York, US",NaN,NaN,2,0
1,"Abelson, Mrs. Anna (née Wizosky?)",28,Russia,Cherbourg,"New York, New York, US",10,NaN,2,1
2,"Andrew, Mr. Edgar Samuel",17,"San Ambrosio, Córdoba, Argentina",Southampton,"Trenton, New Jersey, US",NaN,NaN,2,0
3,"Andrew, Mr. Frank Thomas",30,"Redruth, Cornwall, England",Southampton,"Houghton, Michigan, US",NaN,NaN,2,0
4,"Angle, Mr. William A.",32,"Warwick, Warwickshire, England",Southampton,New York City,NaN,NaN,2,0

In [7]:
third_class = pd.read_html('https://en.wikipedia.org/wiki/Passengers_of_the_Titanic', header=0)[3]
third_class['pclass'] = 3
third_class.columns = third_class.columns.str.strip().str.lower()
third_class.hometown = third_class['hometown'] + ', ' + third_class['home country']
third_class.drop('home country', axis=1, inplace=True)
print(third_class.shape)
third_class.head()

(708, 8)

,name,age,hometown,boarded,destination,lifeboat,body,pclass
0,"Abbing, Mr. Anthony",40,"Cincinnati, Ohio, US",Southampton,"Cincinnati, Ohio, US",NaN,NaN,3
1,"Abbott, Mrs. Rhoda Mary (née Hunt)",39,"East Providence, Rhode Island, US",Southampton,"East Providence, Rhode Island, US",A,NaN,3
2,"Abbott, Mr. Rossmore Edward",16,"East Providence, Rhode Island, US",Southampton,"East Providence, Rhode Island, US",NaN,190MB,3
3,"Abbott, Mr. Eugene Joseph",14,"East Providence, Rhode Island, US",Southampton,"East Providence, Rhode Island, US",NaN,NaN,3
4,"Abd al-Khaliq, Mr. Farid Qasim Husayn",18,"Shana, Syria",Cherbourg,New York City,NaN,NaN,3

In [8]:
rows = soup.select_one('table:nth-of-type(4)').find_all('tr')
psurvived = []
for row in rows[1:]:
    cells = row.find_all('td')
    pname = cells[0].get_text()
    if row.has_attr('style'):
        psurvived.append((pname, 1))
    else:
        psurvived.append((pname, 0))

survived = pd.DataFrame(psurvived, columns=['name', 'survived'])
# survived.head()
pthird_class = pd.merge(third_class, survived, on='name')
pthird_class.head()

,name,age,hometown,boarded,destination,lifeboat,body,pclass,survived
0,"Abbing, Mr. Anthony",40,"Cincinnati, Ohio, US",Southampton,"Cincinnati, Ohio, US",NaN,NaN,3,0
1,"Abbott, Mrs. Rhoda Mary (née Hunt)",39,"East Providence, Rhode Island, US",Southampton,"East Providence, Rhode Island, US",A,NaN,3,1
2,"Abbott, Mr. Rossmore Edward",16,"East Providence, Rhode Island, US",Southampton,"East Providence, Rhode Island, US",NaN,190MB,3,0
3,"Abbott, Mr. Eugene Joseph",14,"East Providence, Rhode Island, US",Southampton,"East Providence, Rhode Island, US",NaN,NaN,3,0
4,"Abd al-Khaliq, Mr. Farid Qasim Husayn",18,"Shana, Syria",Cherbourg,New York City,NaN,NaN,3,0

## Concat

In [9]:
passengers = pd.concat([pfirst_class, psecond_class, pthird_class], ignore_index=True)
print(passengers.shape)
print(passengers.info())
passengers.sample(5)

(1294, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1294 entries, 0 to 1293
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         1294 non-null   object
 1   age          1294 non-null   object
 2   hometown     1257 non-null   object
 3   boarded      1291 non-null   object
 4   destination  1293 non-null   object
 5   lifeboat     495 non-null    object
 6   body         132 non-null    object
 7   pclass       1294 non-null   int64
 8   survived     1294 non-null   int64
dtypes: int64(2), object(7)
memory usage: 91.1+ KB
None

,name,age,hometown,boarded,destination,lifeboat,body,pclass,survived
358,"Byles, Father Thomas Roussel Davids",42,"London, England",Southampton,"Jacksonville, Florida, US",NaN,NaN,2,0
429,"Harris, Mr. Walter",30,"London, England",Southampton,New York City,NaN,NaN,2,0
171,"Jones, Mr. Charles Cresson",46,"Bennington, Vermont, US",Southampton,"Bennington, Vermont, US",NaN,80MB,1,0
71,"Cherry, Miss Gladys",30,"London, England, UK",Southampton,"Vancouver, British Columbia, Canada",8,NaN,1,1
328,"Angle, Mrs. Florence Agnes ""Mary"" (née Hughes)",36,"Warwick, Warwickshire, England",Southampton,New York City,11,NaN,2,1

In [10]:
passengers.isnull().sum()

name              0
age               0
hometown         37
boarded           3
destination       1
lifeboat        799
body           1162
pclass            0
survived          0
dtype: int64

In [11]:
# extracting surnames
surnames = passengers.name.str.extract(r'(?P<surname>.*), (?P<title>[^\s]+) (?P<fmname>.*)')
passengers = pd.concat([passengers, surnames], axis=1)
passengers.head()

,name,age,hometown,boarded,destination,lifeboat,body,pclass,survived,surname,title,fmname
0,"Allen, Miss Elizabeth Walton",29,"St Louis, Missouri, US",Southampton,St Louis,NaN,NaN,1,1,Allen,Miss,Elizabeth Walton
1,"Allison, Mr. Hudson Creighton",30,"Montreal, Quebec, Canada",Southampton,"Montreal, Quebec, Canada",NaN,135MB,1,0,Allison,Mr.,Hudson Creighton
2,"and chauffeur, Mr. George Swane[70]",19,NaN,Southampton,"Montreal, Quebec, Canada",NaN,294MB,1,0,and chauffeur,Mr.,George Swane[70]
3,"and cook, Miss Amelia Mary ""Mildred"" Brown[70]",18,"London, England, UK",Southampton,"Montreal, Quebec, Canada",11,NaN,1,1,and cook,Miss,"Amelia Mary ""Mildred"" Brown[70]"
4,"Allison, Mrs. Bessie Waldo (née Daniels)",25,"Montreal, Quebec, Canada",Southampton,"Montreal, Quebec, Canada",NaN,NaN,1,0,Allison,Mrs.,Bessie Waldo (née Daniels)

In [12]:
passengers.tail()

,name,age,hometown,boarded,destination,lifeboat,body,pclass,survived,surname,title,fmname
1289,"Youssef, Mr. Gerios (Sam'aan)",45,"Hardîne, Syria",Cherbourg,"Wilkes-Barre, Pennsylvania, US",NaN,NaN,3,0,Youssef,Mr.,Gerios (Sam'aan)
1290,"Zajib Qiyamah, Miss Adal ""Jane""",15,"El Shweir, Syria",Cherbourg,"Brooklyn, New York, US",C,NaN,3,1,Zajib Qiyamah,Miss,"Adal ""Jane"""
1291,"Zakarian, Mr. Haroutyun Der",27,"Kiğı, Turkey",Cherbourg,"Brantford, Ontario, Canada",NaN,NaN,3,0,Zakarian,Mr.,Haroutyun Der
1292,"Zakarian, Mr. Mapri Der",22,"Kiğı, Turkey",Cherbourg,"Brantford, Ontario, Canada",NaN,304MB,3,0,Zakarian,Mr.,Mapri Der
1293,"Zimmermann, Mr. Leo",29,"Todtmoos, Germany",Southampton,"Saskatoon, Saskatchewan, Canada",NaN,NaN,3,0,Zimmermann,Mr.,Leo

In [13]:
print(passengers.title.value_counts(dropna=False))
female = ['Miss', 'Mrs.', 'Doña', 'Countess', 'Lady']
male = ['Mr.', 'Mr', 'Captain', 'Sir', 'Don', 'Major', 'The', 'Reverend', 'Father', 'Colonel', 'Major', 'Don', 'Master', 'Dr.']

Mr.         753
Miss        261
Mrs.        190
Master       58
Dr.           8
Colonel       5
Father        4
Reverend      3
The           2
Major         2
NaN           1
Don           1
Lady          1
Doña          1
Countess      1
Sir           1
Captain       1
Mr            1
Name: title, dtype: int64

In [14]:
passengers.loc[passengers.title == 'Major']

,name,age,hometown,boarded,destination,lifeboat,body,pclass,survived,surname,title,fmname
45,"Butt, Major Archibald Willingham",46,"Washington, D.C., US",Southampton,"Washington, D.C., US",NaN,NaN,1,0,Butt,Major,Archibald Willingham
228,"Peuchen, Major Arthur Godfrey",52,"Toronto, Ontario, Canada",Southampton,"Toronto, Ontario, Canada",6,NaN,1,1,Peuchen,Major,Arthur Godfrey

In [15]:
def set_sex(row):
#     print(row)
    if row.title in female:
        return 'female'
    elif row.title in male:
        return 'male'
    else:
        return 'unknown'
    
passengers['sex'] = passengers.apply(set_sex, axis=1)
print(passengers['sex'].value_counts())
passengers.head()

male       839
female     454
unknown      1
Name: sex, dtype: int64

,name,age,hometown,boarded,destination,lifeboat,body,pclass,survived,surname,title,fmname,sex
0,"Allen, Miss Elizabeth Walton",29,"St Louis, Missouri, US",Southampton,St Louis,NaN,NaN,1,1,Allen,Miss,Elizabeth Walton,female
1,"Allison, Mr. Hudson Creighton",30,"Montreal, Quebec, Canada",Southampton,"Montreal, Quebec, Canada",NaN,135MB,1,0,Allison,Mr.,Hudson Creighton,male
2,"and chauffeur, Mr. George Swane[70]",19,NaN,Southampton,"Montreal, Quebec, Canada",NaN,294MB,1,0,and chauffeur,Mr.,George Swane[70],male
3,"and cook, Miss Amelia Mary ""Mildred"" Brown[70]",18,"London, England, UK",Southampton,"Montreal, Quebec, Canada",11,NaN,1,1,and cook,Miss,"Amelia Mary ""Mildred"" Brown[70]",female
4,"Allison, Mrs. Bessie Waldo (née Daniels)",25,"Montreal, Quebec, Canada",Southampton,"Montreal, Quebec, Canada",NaN,NaN,1,0,Allison,Mrs.,Bessie Waldo (née Daniels),female

In [16]:
passengers.loc[339, 'sex'] = 'female'

In [17]:
passengers.loc[passengers.sex == 'unknown']

,name,age,hometown,boarded,destination,lifeboat,body,pclass,survived,surname,title,fmname,sex
336,Beane. Mrs. Ethel (née Clarke),19,"Norwich, Norfolk, England",Southampton,New York City,13,NaN,2,1,NaN,NaN,NaN,unknown

In [18]:
print(passengers.shape)
passengers.dropna(axis=0, subset='name', inplace=True)
print(passengers.shape)

(1294, 13)
(1294, 13)

In [19]:
print(passengers['sex'].value_counts())
passengers.head()

male       839
female     454
unknown      1
Name: sex, dtype: int64

,name,age,hometown,boarded,destination,lifeboat,body,pclass,survived,surname,title,fmname,sex
0,"Allen, Miss Elizabeth Walton",29,"St Louis, Missouri, US",Southampton,St Louis,NaN,NaN,1,1,Allen,Miss,Elizabeth Walton,female
1,"Allison, Mr. Hudson Creighton",30,"Montreal, Quebec, Canada",Southampton,"Montreal, Quebec, Canada",NaN,135MB,1,0,Allison,Mr.,Hudson Creighton,male
2,"and chauffeur, Mr. George Swane[70]",19,NaN,Southampton,"Montreal, Quebec, Canada",NaN,294MB,1,0,and chauffeur,Mr.,George Swane[70],male
3,"and cook, Miss Amelia Mary ""Mildred"" Brown[70]",18,"London, England, UK",Southampton,"Montreal, Quebec, Canada",11,NaN,1,1,and cook,Miss,"Amelia Mary ""Mildred"" Brown[70]",female
4,"Allison, Mrs. Bessie Waldo (née Daniels)",25,"Montreal, Quebec, Canada",Southampton,"Montreal, Quebec, Canada",NaN,NaN,1,0,Allison,Mrs.,Bessie Waldo (née Daniels),female