<a href="https://colab.research.google.com/github/gitmystuff/DSChunks/blob/main/Transformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Transformers

## Abstract Ideas

* https://energywavetheory.com/equations/emc2/
* https://en.wikipedia.org/wiki/Musical_note
* https://www.dailyarthub.com/shop/objects/free-science-symbols-clip-art-set/

## Neural Networks

### ANNs

* https://en.wikipedia.org/wiki/Neural_network_(machine_learning)

### CNNs

* https://en.wikipedia.org/wiki/Convolutional_neural_network
* https://www.ibm.com/topics/convolutional-neural-networks
* https://ieeexplore.ieee.org/document/726791

### RNNs

* https://en.wikipedia.org/wiki/Recurrent_neural_network
* x in time t, is input to RNN unit, and outputs a hidden vector, or state, at time t

#### Types of RNNs

* https://www.educative.io/answers/what-are-the-types-of-rnn

### LSTM

https://en.wikipedia.org/wiki/Long_short-term_memory

* Cell
* Input Gate
* Output Gate
* Forget Gate
* Activation Function (represented by $\sigma$)
* https://www.researchgate.net/figure/Structure-of-the-LSTM-cell-and-equations-that-describe-the-gates-of-an-LSTM-cell_fig5_329362532
* The cell state represents the memory of the network, information over time, while the hidden state contains the (new) processed information that is passed to the next time step

### Seq2Seq

* Encoder / Decoder
* https://en.wikipedia.org/wiki/Seq2seq
* https://www.researchgate.net/figure/Seq2Seq-model-neural-encoder-and-decoder-32_fig4_334023532
* h(t), a compressed representation (vector) of the input (thought vector), is between encoder and decoder
* A problem with Seq2Seq is using long passages, long-term dependencies, and remembering context
* h(t) always has the same size and can cause a bottle neck

### LSTM vs Seq2Seq

* Both are many to many models
* LSTMs are building blocks
* Seq2Seq is an architecture built from encoder LSTM and decoder LSTM, etc.

### All You Need is Attention

* For each output token, we want to know which input to pay attention to by using weights
* https://theaisummer.com/attention/
* Attention layer is a mapping of inputs to outputs

#### No More RNN

* RNNs are slow because they are sequential
* Cannot be parallelized
* Vanishing Gradients

### Summary

(RNN, Seq2Seq, Attention, Transformers)

* Attention is all you need - https://arxiv.org/abs/1706.03762
* The attention mechanism allows the model to focus on different parts of the input text. This helps the model to generate more accurate predictions. This allows words in a text sequence to pay attention to the earlier words in the sequence. This helps to model large text sequences in a correct manner.
* This process can be thought of as autoregression (what is the next best word)
* Transformers are big and slow but can be done in parallel, unlike RNNs
* Provides longer range than LSTM
* Created for RNNs (LSTMs), but transformers only use attention
* Assign varying levels of importance to different parts of a sentence or text
* Capture contextual information effectively
* Understand the relationships between words
* Extract the most relevant parts of a query while disregarding less important ones
* Comprehend pronouns, two-sided words, and related sentences more effectively
* Generate coherent answers for queries

## LLMs - Tokens and Transformers

* Completion vs Chat
* Chat needs context, memory
* LangChain
* Transfer Learning: In transfer learning, a machine exploits the knowledge gained from a previous task to improve generalization about another. For example, in training a classifier to predict whether an image contains food, you could use the knowledge it gained during training to recognize drinks. - https://builtin.com/data-science/transfer-learning
* HuggingFace Transformers - https://huggingface.co/models

Transformer Architecture

* https://magazine.sebastianraschka.com/p/understanding-and-coding-self-attention

Encoding vs Decoding

However, the main difference is that encoders are designed to learn embeddings that can be used for various predictive modeling tasks such as classification. In contrast, decoders are designed to generate new texts, for example, answering user queries.

https://magazine.sebastianraschka.com/p/understanding-encoder-and-decoder

Attention

* The chicken crossed the road because it was hungry
* The chicken crossed the road because it was the way home
* What is it?

Query, Key, Value

* The query vector represents the current focus of the LLM, like the central theme of the sentence. The key and value vectors hold information about each word, like its definition and role in the context.
* https://www.thecloudgirl.dev/blog/how-attention-makes-llms-powerful

Pipeline

<pre>
from transformers import pipeline
</pre>

* Text Processing
* Tokenize Data
* Model
* Numerical Predictions
* Post Processing
* Human Readable Predictions

Highlights

* Tokenizer
* Sentiment Analysis
* Text Generation
* Masked Language Modeling
* NER
* Summarization
* Translation
* Question and Answer
* Zero-Shot Classification

Source

* https://deeplearningcourses.com/c/data-science-transformers-nlp

### Transformer

* Stack of attention layers
* Pre trained stack of mappings from Encoder to Decoder
* The attention function can be considered a mapping between a query and a set of key-value pairs to an output
* Query, Key, Value

Sources

* https://arxiv.org/abs/1706.03762
* https://machinelearningmastery.com/the-transformer-attention-mechanism/
* https://www.linkedin.com/pulse/unpacking-query-key-value-transformers-analogy-database-mohamed-nabil/

### Tokenizer

* Different models yield different outputs
* Padding and Truncation

In [ ]:
from transformers import AutoTokenizer

model = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(model)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
tokenizer('happy friday')

{'input_ids': [101, 3407, 5958, 102], 'token_type_ids': [0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1]}

In [ ]:
tokens = tokenizer.tokenize('happy friday')
print(tokens)
ids = tokenizer.convert_tokens_to_ids(tokens)
print(ids)
print(tokenizer.decode(ids))
ids = tokenizer.encode('happy friday')
print(ids)
tokenizer.decode(ids)

['happy', 'friday']
[3407, 5958]
happy friday
[101, 3407, 5958, 102]

'[CLS] happy friday [SEP]'

In [ ]:
data = [
    'I like cats.',
    'Do you like cats too?',
    'Wow, those cats like really know how to play groovy music.',
]
tokenizer(data)

{'input_ids': [[101, 1045, 2066, 8870, 1012, 102], [101, 2079, 2017, 2066, 8870, 2205, 1029, 102], [101, 10166, 1010, 2216, 8870, 2066, 2428, 2113, 2129, 2000, 2377, 24665, 9541, 10736, 2189, 1012, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

### Sentiment Analysis

In [ ]:
from transformers import pipeline

sa = pipeline('sentiment-analysis')
print(sa('I love fridays'))
print(sa('I am sad to see the class end on Fridays'))
print(sa('I have mixed emotions about Fridays'))

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

[{'label': 'POSITIVE', 'score': 0.9998154044151306}]
[{'label': 'NEGATIVE', 'score': 0.9976856708526611}]
[{'label': 'NEGATIVE', 'score': 0.9801062941551208}]

In [ ]:
sa(['i really like talking during class',
    'i wish it was a little more quiet because this is driving me cuckoo'])

[{'label': 'POSITIVE', 'score': 0.9988310933113098},
 {'label': 'NEGATIVE', 'score': 0.9967963099479675}]

### Text Generation

In [ ]:
url = 'https://raw.githubusercontent.com/gitmystuff/Datasets/main/alice%20in%20wonderland%20chapter%201.txt'

from transformers import pipeline
import requests

response = requests.get(url)
data = response.text
print(data)

CHAPTER I.
Down the Rabbit-Hole
Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, “and what is the use of a book,” thought Alice “without pictures or conversations?”

So she was considering in her own mind (as well as she could, for the hot day made her feel very sleepy and stupid), whether the pleasure of making a daisy-chain would be worth the trouble of getting up and picking the daisies, when suddenly a White Rabbit with pink eyes ran close by her.

There was nothing so very remarkable in that; nor did Alice think it so very much out of the way to hear the Rabbit say to itself, “Oh dear! Oh dear! I shall be late!” (when she thought it over afterwards, it occurred to her that she ought to have wondered at this, but at the time it all seemed quite natural); but when the Rabbit actually took a watch out of its waistcoat-pocket, and looked at it, and then hurried on, Alice started to her feet, for it flashed across her mind that she had never before seen a rabbit with either a waistcoat-pocket, or a watch to take out of it, and burning with curiosity, she ran across the field after it, and fortunately was just in time to see it pop down a large rabbit-hole under the hedge.

In another moment down went Alice after it, never once considering how in the world she was to get out again.

The rabbit-hole went straight on like a tunnel for some way, and then dipped suddenly down, so suddenly that Alice had not a moment to think about stopping herself before she found herself falling down a very deep well.

Either the well was very deep, or she fell very slowly, for she had plenty of time as she went down to look about her and to wonder what was going to happen next. First, she tried to look down and make out what she was coming to, but it was too dark to see anything; then she looked at the sides of the well, and noticed that they were filled with cupboards and book-shelves; here and there she saw maps and pictures hung upon pegs. She took down a jar from one of the shelves as she passed; it was labelled “ORANGE MARMALADE”, but to her great disappointment it was empty: she did not like to drop the jar for fear of killing somebody underneath, so managed to put it into one of the cupboards as she fell past it.

“Well!” thought Alice to herself, “after such a fall as this, I shall think nothing of tumbling down stairs! How brave they’ll all think me at home! Why, I wouldn’t say anything about it, even if I fell off the top of the house!” (Which was very likely true.)

Down, down, down. Would the fall never come to an end? “I wonder how many miles I’ve fallen by this time?” she said aloud. “I must be getting somewhere near the centre of the earth. Let me see: that would be four thousand miles down, I think—” (for, you see, Alice had learnt several things of this sort in her lessons in the schoolroom, and though this was not a very good opportunity for showing off her knowledge, as there was no one to listen to her, still it was good practice to say it over) “—yes, that’s about the right distance—but then I wonder what Latitude or Longitude I’ve got to?” (Alice had no idea what Latitude was, or Longitude either, but thought they were nice grand words to say.)

Presently she began again. “I wonder if I shall fall right through the earth! How funny it’ll seem to come out among the people that walk with their heads downward! The Antipathies, I think—” (she was rather glad there was no one listening, this time, as it didn’t sound at all the right word) “—but I shall have to ask them what the name of the country is, you know. Please, Ma’am, is this New Zealand or Australia?” (and she tried to curtsey as she spoke—fancy curtseying as you’re falling through the air! Do you think you could manage it?) “And what an ignorant little girl she’ll think me for asking! No, it’ll never do to ask: perhaps I shall see it written up somewhere.”

Down, down, down. There was nothing else to do, so Alice soon began talking again. “Dinah’ll miss me very much to-night, I should think!” (Dinah was the cat.) “I hope they’ll remember her saucer of milk at tea-time. Dinah my dear! I wish you were down here with me! There are no mice in the air, I’m afraid, but you might catch a bat, and that’s very like a mouse, you know. But do cats eat bats, I wonder?” And here Alice began to get rather sleepy, and went on saying to herself, in a dreamy sort of way, “Do cats eat bats? Do cats eat bats?” and sometimes, “Do bats eat cats?” for, you see, as she couldn’t answer either question, it didn’t much matter which way she put it. She felt that she was dozing off, and had just begun to dream that she was walking hand in hand with Dinah, and saying to her very earnestly, “Now, Dinah, tell me the truth: did you ever eat a bat?” when suddenly, thump! thump! down she came upon a heap of sticks and dry leaves, and the fall was over.

Alice was not a bit hurt, and she jumped up on to her feet in a moment: she looked up, but it was all dark overhead; before her was another long passage, and the White Rabbit was still in sight, hurrying down it. There was not a moment to be lost: away went Alice like the wind, and was just in time to hear it say, as it turned a corner, “Oh my ears and whiskers, how late it’s getting!” She was close behind it when she turned the corner, but the Rabbit was no longer to be seen: she found herself in a long, low hall, which was lit up by a row of lamps hanging from the roof.

There were doors all round the hall, but they were all locked; and when Alice had been all the way down one side and up the other, trying every door, she walked sadly down the middle, wondering how she was ever to get out again.

Suddenly she came upon a little three-legged table, all made of solid glass; there was nothing on it except a tiny golden key, and Alice’s first thought was that it might belong to one of the doors of the hall; but, alas! either the locks were too large, or the key was too small, but at any rate it would not open any of them. However, on the second time round, she came upon a low curtain she had not noticed before, and behind it was a little door about fifteen inches high: she tried the little golden key in the lock, and to her great delight it fitted!

Alice opened the door and found that it led into a small passage, not much larger than a rat-hole: she knelt down and looked along the passage into the loveliest garden you ever saw. How she longed to get out of that dark hall, and wander about among those beds of bright flowers and those cool fountains, but she could not even get her head through the doorway; “and even if my head would go through,” thought poor Alice, “it would be of very little use without my shoulders. Oh, how I wish I could shut up like a telescope! I think I could, if I only knew how to begin.” For, you see, so many out-of-the-way things had happened lately, that Alice had begun to think that very few things indeed were really impossible.

There seemed to be no use in waiting by the little door, so she went back to the table, half hoping she might find another key on it, or at any rate a book of rules for shutting people up like telescopes: this time she found a little bottle on it, (“which certainly was not here before,” said Alice,) and round the neck of the bottle was a paper label, with the words “DRINK ME,” beautifully printed on it in large letters.

It was all very well to say “Drink me,” but the wise little Alice was not going to do that in a hurry. “No, I’ll look first,” she said, “and see whether it’s marked ‘poison’ or not”; for she had read several nice little histories about children who had got burnt, and eaten up by wild beasts and other unpleasant things, all because they would not remember the simple rules their friends had taught them: such as, that a red-hot poker will burn you if you hold it too long; and that if you cut your finger very deeply with a knife, it usually bleeds; and she had never forgotten that, if you drink much from a bottle marked “poison,” it is almost certain to disagree with you, sooner or later.

However, this bottle was not marked “poison,” so Alice ventured to taste it, and finding it very nice, (it had, in fact, a sort of mixed flavour of cherry-tart, custard, pine-apple, roast turkey, toffee, and hot buttered toast,) she very soon finished it off.

*      *      *      *      *      *      *

    *      *      *      *      *      *

*      *      *      *      *      *      *
“What a curious feeling!” said Alice; “I must be shutting up like a telescope.”

And so it was indeed: she was now only ten inches high, and her face brightened up at the thought that she was now the right size for going through the little door into that lovely garden. First, however, she waited for a few minutes to see if she was going to shrink any further: she felt a little nervous about this; “for it might end, you know,” said Alice to herself, “in my going out altogether, like a candle. I wonder what I should be like then?” And she tried to fancy what the flame of a candle is like after the candle is blown out, for she could not remember ever having seen such a thing.

After a while, finding that nothing more happened, she decided on going into the garden at once; but, alas for poor Alice! when she got to the door, she found she had forgotten the little golden key, and when she went back to the table for it, she found she could not possibly reach it: she could see it quite plainly through the glass, and she tried her best to climb up one of the legs of the table, but it was too slippery; and when she had tired herself out with trying, the poor little thing sat down and cried.

“Come, there’s no use in crying like that!” said Alice to herself, rather sharply; “I advise you to leave off this minute!” She generally gave herself very good advice, (though she very seldom followed it), and sometimes she scolded herself so severely as to bring tears into her eyes; and once she remembered trying to box her own ears for having cheated herself in a game of croquet she was playing against herself, for this curious child was very fond of pretending to be two people. “But it’s no use now,” thought poor Alice, “to pretend to be two people! Why, there’s hardly enough of me left to make one respectable person!”

Soon her eye fell on a little glass box that was lying under the table: she opened it, and found in it a very small cake, on which the words “EAT ME” were beautifully marked in currants. “Well, I’ll eat it,” said Alice, “and if it makes me grow larger, I can reach the key; and if it makes me grow smaller, I can creep under the door; so either way I’ll get into the garden, and I don’t care which happens!”

She ate a little bit, and said anxiously to herself, “Which way? Which way?”, holding her hand on the top of her head to feel which way it was growing, and she was quite surprised to find that she remained the same size: to be sure, this generally happens when one eats cake, but Alice had got so much into the way of expecting nothing but out-of-the-way things to happen, that it seemed quite dull and stupid for life to go on in the common way.

So she set to work, and very soon finished off the cake.

*      *      *      *      *      *      *

    *      *      *      *      *      *

*      *      *      *      *      *      *

In [ ]:
lines = data.splitlines()
lines[2]

'Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, “and what is the use of a book,” thought Alice “without pictures or conversations?”'

In [ ]:
gen = pipeline('text-generation', max_length=100)
print(gen(lines[2]))

No model was supplied, defaulted to openai-community/gpt2 and revision 6c0e608 (https://huggingface.co/openai-community/gpt2).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

[{'generated_text': "Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do: once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it, “and what is the use of a book,” thought Alice “without pictures or conversations?” There was nothing in it, though. There was something that didn't quite fit. For the first time for some time, she became"}]

In [ ]:
import textwrap

def wrap(x):
  return textwrap.fill(x, replace_whitespace=False, fix_sentence_endings=True)

prompt = 'The book had no pictures or conversations in it, and what is the use of a book, thought Alice without pictures or conversations'
out = gen(prompt, max_length=300)
print(wrap(out[0]['generated_text']))

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

The book had no pictures or conversations in it, and what is the use
of a book, thought Alice without pictures or conversations, without a
feeling, without any sound, without anything else?

A. The book is
written before there is anything.

B. The books do not meet the
requirements and to be fulfilled the books of the people do not meet
the requirements.  But they are not in this book to be filled.

C. The
people and the books meet the requirements of the people.  The books
meet the requirements of the people because of the people.

A. When
the people meet the requirements of the people to be fulfilled the
books of the people are not in the book.  The books can only be found
in the things or characters.  The books must be found in any parts or
places that the people may have no idea.

A. When the people meet the
conditions are written and when the books meet those conditions I do
not know why.

B. I need to think of things as such, in their own
words.  I find those things they do not know to be the things that I
do not know to be.

A. And if you ask, what are the causes and, if
there are causes I do not know, what are the causes and who are the
causes and what is the cause (of the books)?

B. The causes.

A. The
books do not meet the requirements of books

### Masked Language Modeling

In [ ]:
!wget -nc https://raw.githubusercontent.com/gitmystuff/Datasets/main/news_stories.csv

--2024-03-29 21:12:49--  https://raw.githubusercontent.com/gitmystuff/Datasets/main/news_stories.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20572175 (20M) [text/plain]
Saving to: ‘news_stories.csv’

news_stories.csv    100%[===================>]  19.62M  --.-KB/s    in 0.1s

2024-03-29 21:12:49 (141 MB/s) - ‘news_stories.csv’ saved [20572175/20572175]

In [ ]:
import pandas as pd

df = pd.read_csv('news_stories.csv')
df.head()

,link,headline,category,short_description,authors,date
0,https://www.huffingtonpost.comhttp://nymag.com...,The Single American Woman,WOMEN,By the time I walked down the aisle — or rathe...,NaN,2016-02-22
1,https://www.huffingtonpost.com/entry/a-tour-gu...,Taking Fervent Capitalists To A French Doctor,TRAVEL,"Determined to ""pay their own way,"" John and Ja...","Rick Steves, Contributor\nContributor",2012-10-19
2,https://www.huffingtonpost.com/entry/hayden-pa...,Hayden Panettiere Flashes A Big Smile During F...,ENTERTAINMENT,😊🌴🌊💞👪,Cole Delbyck,2016-03-07
3,https://www.huffingtonpost.com/entry/hostess-g...,Hostess Gifts for the Holidays,STYLE,NaN,"Colleen Mullaney, ContributorLifestyle expert",2014-12-11
4,https://www.huffingtonpost.com/entry/medical-m...,This Is The First U.S. School To Allow Marijua...,POLITICS,"""I know there are so many kids in this state a...",Sebastian Murdock,2015-11-12

In [ ]:
df = df[df['category'].isin(['POLITICS', 'TRAVEL', 'WEDDINGS', 'EDUCATION', 'SCIENCE'])]
df['category'].value_counts()

POLITICS     10659
TRAVEL        2920
WEDDINGS      1120
SCIENCE        649
EDUCATION      296
Name: category, dtype: int64

In [ ]:
cats = 'POLITICS'
texts = df[df['category'] == cats]['short_description']
texts = texts.reset_index()
texts.drop('index', axis=1, inplace=True)
texts.head()

                                   short_description
0  "I know there are so many kids in this state a...
1  Jon Stewart will ask them to make up for it ne...
2                                                NaN
3  He's not saying Moore should go "if" the sexua...
4      International trade law must be enforced now.

In [ ]:
texts.iloc[3]['short_description']

'He\'s not saying Moore should go "if" the sexual assault allegations are true. He\'s telling him to get out now.'

In [ ]:
mlm = pipeline('fill-mask')

No model was supplied, defaulted to distilbert/distilroberta-base and revision ec58a5b (https://huggingface.co/distilbert/distilroberta-base).
Using a pipeline without specifying a model name and revision in production is not recommended.
Some weights of the model checkpoint at distilbert/distilroberta-base were not used when initializing RobertaForMaskedLM: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [ ]:
mlm('He\'s not saying <mask> should go if the sexual assault allegations are true. He\'s telling him to get out now')

[{'score': 0.13113802671432495,
  'token': 37,
  'token_str': ' he',
  'sequence': "He's not saying he should go if the sexual assault allegations are true. He's telling him to get out now"},
 {'score': 0.08181885629892349,
  'token': 6669,
  'token_str': ' Weinstein',
  'sequence': "He's not saying Weinstein should go if the sexual assault allegations are true. He's telling him to get out now"},
 {'score': 0.07349928468465805,
  'token': 79,
  'token_str': ' she',
  'sequence': "He's not saying she should go if the sexual assault allegations are true. He's telling him to get out now"},
 {'score': 0.03797372058033943,
  'token': 9858,
  'token_str': ' Cosby',
  'sequence': "He's not saying Cosby should go if the sexual assault allegations are true. He's telling him to get out now"},
 {'score': 0.03462321311235428,
  'token': 140,
  'token_str': ' Trump',
  'sequence': "He's not saying Trump should go if the sexual assault allegations are true. He's telling him to get out now"}]

### NER

* Treebank - https://en.wikipedia.org/wiki/Treebank

In [ ]:
# !pip install datasets

In [ ]:
# from datasets import load_dataset

# dataset = load_dataset("conll2003")
# dataset

In [ ]:
# import pandas as pd

# df = pd.DataFrame(dataset['validation'])
# df.head()

### Summarization

### Translation

* https://huggingface.co/search/full-text?q=hindi+english+datasets

In [ ]:
# !wget -nc http://storage.googleapis.com/download.tensorflow.org/data/spa-eng.zip
# !unzip -nq spa-eng.zip
# !ls

### Question Answer

### Zero Shot Classification

In [ ]:
from transformers import pipeline

zsc = pipeline('zero-shot-classification')

No model was supplied, defaulted to facebook/bart-large-mnli and revision c626438 (https://huggingface.co/facebook/bart-large-mnli).
Using a pipeline without specifying a model name and revision in production is not recommended.

In [ ]:
zsc('This is really cool', candidate_labels=['positive', 'negative'])

{'sequence': 'This is really cool',
 'labels': ['positive', 'negative'],
 'scores': [0.9978017807006836, 0.002198190428316593]}

In [ ]:
idx = 20
cats = list(set(df['category']))
print(cats)
print(df.iloc[idx]['short_description'])
print(df.iloc[idx]['category'])

['SCIENCE', 'WEDDINGS', 'POLITICS', 'EDUCATION', 'TRAVEL']
Overnight, Paul Revere became one of America's greatest heroes. Today, he is practically an industry in Boston. You can tour his house, see his portrait, buy reproductions of his silver work, have a drink in his favorite tavern and even leave pennies on his grave.
TRAVEL

In [ ]:
zsc(df.iloc[idx]['short_description'], candidate_labels=cats)

{'sequence': "Overnight, Paul Revere became one of America's greatest heroes. Today, he is practically an industry in Boston. You can tour his house, see his portrait, buy reproductions of his silver work, have a drink in his favorite tavern and even leave pennies on his grave.",
 'labels': ['TRAVEL', 'EDUCATION', 'WEDDINGS', 'POLITICS', 'SCIENCE'],
 'scores': [0.5797111392021179,
  0.17192208766937256,
  0.11337940394878387,
  0.07679370790719986,
  0.05819365382194519]}